### ISSUE TITLE
Incorrect signature as a result of GET URL parameters

### ISSUE THREAD

**Issue by enviscient** [NetSPI/AWSSigner#15]
There is an issue that results in incorrect signatures that appears to be the result of GET parameter names and ordering.  By reordering the parameters its possible to have a resulting correct signature.  Changing the parameter value from a string to a integer, or vice versa did not show any change in behavior.  Attempts at encoding did not help.  Examples of parameter strings that resulted in correct and incorrect signatures are below.

**Incorrect sig:** `GET /?pnum=1111111111&userFirstname=Bob&timestamp=1642407088910`
**Incorrect sig:** `GET /?userFirstname=Bob&pnum=1111111111&timestamp=1642407088910`
**Correct sig:** `GET /?pnum=1111111111&timestamp=1642407088910&userFirstname=Bob`
// --------------------
**Incorrect sig:** `GET /?userFirstname=Bob&userLastname=SmithuserEmail=Bob.Smith%40example.com&timestamp=1564258409354`
**Incorrect sig:** `GET /?userFirstname=Bob&userLastname=Smith&timestamp=1564258409354&userEmail=Bob.Smith%40example.com`
**Incorrect sig:** `GET /?timestamp=1564258409354&userFirstname=Bob&userLastname=Smith&userEmail=Bob.Smith%40example.com`
**Incorrect sig:** `GET /?timestamp=1564258409354&userFirstname=1111111111&userLastname=1111111111&userEmail=1111111111`
**Incorrect sig:** `GET /?timestamp=1564258409354&e=Bob.Smith%40example.com&f=Bob&l=Smith`
**Incorrect sig:** `GET /?%74%69%6d%65%73%74%61%6d%70%3d%31%35%36%34%32%35%38%34%30%39%33%35%34%26%75%73%65%72%45%6d%61%69%6c%3d%42%6f%62%2e%53%6d%69%74%68%25%34%30%65%78%61%6d%70%6c%65%2e%63%6f%6d%26%75%73%65%72%46%69%72%73%74%6e%61%6d%65%3d%42%6f%62%26%75%73%65%72%4c%61%73%74%6e%61%6d%65%3d%53%6d%69%74%68`
**Correct sig:** `GET /?timestamp=1564258409354&userEmail=Bob.Smith%40example.com&userFirstname=Bob&userLastname=Smith`
**Correct sig:** `GET /?timestamp=1564258409354&userEmail=11111111111&userFirstname=1111111111&userLastname=1111111111`
// --------------------
**Incorrect sig:** `GET /?username=Example.com_123456&timestamp=1564290688176`
**Correct sig:** `GET /?timestamp=1564290688176&username=Example.com_123456`

**Comment by AndreyRainchik** [comment]
Hello, thanks for reporting the issue! Query strings should be in alphabetical order according to https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html, and we pushed out ab2eba4 which should now do this automatically. We have a new release out now that should include this commit, could you give it a try and see if that works for you?

**Comment by enviscient** [comment]
The new updates appear to have solved the issues that I was experiencing.  I will continue to test.  One thing to note, the new release JAR was built using Java 12, which is not officially supported by Portswigger.

**Comment by egru** [comment]
Thanks for checking that. I reupoaded the jar built with JDK 11.
