### ISSUE TITLE
Feature Requests - Flag modified requests in proxy tab

### ISSUE THREAD

**Issue by securitysamurai** [NetSPI/AWSSigner#25]
Is there any way to highlight to identify AWS Signer is active or use the edited column within the proxy tab? Initially I didn't realize AWS Signer was active and changing the authorization header in my proxy when I had activated it within the Repeater tab.

**Comment by jakekarnes42** [comment]
This feature is implemented in AWS Signer 2.0.0 in PR #30. There should be a comment applied to every signed request indicating that it was signed and which profile was used to sign it. You should be able to observe this wherever that Comment column is included (e.g. the Logger tab, Proxy - HTTP history, etc).
