### ISSUE TITLE
Bug - POST Data Sent Using GET Method Truncates POST Body

### ISSUE THREAD

**Issue by venominfosec** [NetSPI/AWSSigner#27]
### Description

**Issue:** A malformed request that sends POST data using the GET method is not properly signed. The result is a request that truncates that POST body and signs the GET request.

**Proposed Solution:** Ensure that requests are not truncated and that, regardless of the HTTP method used, the entire request is signed. 

### Example (validated using Logger++ in Burp):

**Base Request:**
```
GET /[REDACTED]/capability HTTP/1.1
Host: [REDACTED]
Accept-Encoding: gzip, deflate
Content-Length: 61
User-Agent: aws-cli/1.16.278 Python/3.7.4 Windows/10 botocore/1.13.14
X-Amz-Date: 20200324T182027Z
Authorization: [REDACTED]
Connection: close

{
  [REDACTED]
}
```

**AWS Signer Modified Request:**
```
GET /[REDACTED]/capability HTTP/1.1
Host: [REDACTED]
Accept-Encoding: gzip, deflate
Content-Length: 61
User-Agent: aws-cli/1.16.278 Python/3.7.4 Windows/10 botocore/1.13.14
X-Amz-Date: 20200324T182027Z
Authorization: [REDACTED]
Connection: close
```

**Comment by AndreyRainchik** [comment]
Fixed in latest release, JAR file is available
