### ISSUE TITLE
Multi-part/form-data Not Recognized As SigV4

### ISSUE THREAD

**Issue by sonofapharmacist** [NetSPI/AWSSigner#35]
```
[DEBUG] Handling incoming HTTP message.
[DEBUG] Message is not a SigV4 request.
[DEBUG] Handling incoming HTTP message.
[DEBUG] Ignoring response.
```

The headers do not contain the keys and are instead submitted in the form-data boundaries.

The keys I'm looking to update are x-amz-security-token, policy, and x-amz-signature.  Am I doing it right or should I be looking elsewhere?

**Comment by jakekarnes42** [comment]
Right, the extension is determining if it's a SigV4 request if the x-amz-date and x-amz-signature headers are in the request: https://github.com/NetSPI/AWSSigner/blob/8b12b8dab8b53ba66b78bb94c2474d72e346e8d4/src/main/java/burp/BurpExtender.java#L185-L186

Could you share a little bit more about your use case where the values to be signed are in the body rather than the headers? Is this a request to an AWS service or some other system? An example request would be great.

**Comment by sonofapharmacist** [comment]
Thanks for the reply Jake. 
Here's an example of the POST I do for an upload

```
POST / HTTP/1.1
Host: stuff
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=---------------------------955475617602502893771735763
Content-Length: 3550
Origin: stuff
Referer: stuff
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Te: trailers
Connection: close

-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="key"

stuff/stuff.jpg
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="x-amz-algorithm"

AWS4-HMAC-SHA256
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="x-amz-credential"

stuff/20220628/stuff/s3/aws4_request
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="x-amz-date"

20220628T141751Z
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="x-amz-security-token"

IQstuffZ2X342
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="policy"

eystuff19
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="x-amz-signature"

c9stuff27
-----------------------------955475617602502893771735763
Content-Disposition: form-data; name="file"; filename=";.jpg"
Content-Type: image/jpeg

Hello World

-----------------------------955475617602502893771735763--
```


The S3 bucket is looking for this type of GET request, which returns the policy you see in the POST
```
GET /stuff/?datasource=stuff&clientid=stuff&file_name=stuff.jpg&date=1656425871234 HTTP/2
Host: stuff.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer AtokeN
Cache-Control: no-cache
Pragma: no-cache
Origin: https://stuff
Referer: https://stuff
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Te: trailers
```

Maybe my question ought to be: Is the signer relevant for this type of situation?

Thanks!

**Comment by jakekarnes42** [comment]
You're right. This Burp Suite extension isn't the right tool for the job in this case. This extension inspects the HTTP headers looking for "x-amz-date" and an "authorization" header matching the Sigv4 format. If those are found, it will try to sign the request by updating those headers. 

Updating a signature in the body of a request (as shown in your example) isn't currently supported.
