### ISSUE TITLE
java.lang.NullPointerException error

### ISSUE THREAD

**Issue by superuser5** [NetSPI/AWSSigner#7]
I am using the extension latest version from the release (loaded latest jar file), and i get the "java.lang.NullPointerException" showing in the Error tab. the Output tab shows Signing with profile 1 with key: iuhqwieuhfqilwuehf123423jiuh

burp 2.0.18beta
java comes with burp.

**Comment by egru** [comment]
Well that's no good. I'll take a look.

**Comment by egru** [comment]
I uploaded a new build that fixed a different issue. I was not able to recreate the exception that you're getting however. If you don't have an authorization header in the request, you may get that exception. But all AWS signed requests should have that to begin with.

**Comment by superuser5** [comment]
will retest it. i am trying to compile new version and executing cradlew and cannot find generated jar file for Mac or kali. can i ask for compilation hints on mac/linux?

**Comment by egru** [comment]
I'm using a Mac to compile it, but I tested it with Kali doing the following:

1. git clone https://github.com/NetSPI/AWSSigner.git
2. apt-get install gradle
3. cd AWSSigner
4. gradle build

The compiled jar will be in the AWSSigner/build/libs folder

**Comment by superuser5** [comment]
thank you.
used new version and it worked.
the Authorization header was missing.

where to specify SignedHeaders?

**Comment by superuser5** [comment]
what are the minimum headers should be present for extension to work?

**Comment by egru** [comment]
So right now the extension will look at the Authorization header of a signed request to grab the SignedHeaders. Here's an example of a Sigv4 request:

POST /?Param1=value1 HTTP/1.1
Host:example.amazonaws.com
X-Amz-Date:20150830T123600Z
Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20190101/us-west-1/test/request, **SignedHeaders=cache-control;content-type;host;x-amz-date,** Signature=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

The extension will update the x-amz-date header as well as the authorization header with the relevant AWS credentials, region, and service to calculate the Signature.

**Comment by superuser5** [comment]
thanks this worked.
