### ISSUE TITLE
feature request - sign custom headers

### ISSUE THREAD

**Issue by superuser5** [NetSPI/AWSSigner#8]
Some application request that some custom headers needs to be signed.

is it possible to add extra configuration parameter, so i can specify what additional HTTP headers needs to be signed?

**Comment by jakekarnes42** [comment]
This should be implemented in AWS Signer 2.0.0 in PR #30. To include or omit an HTTP header from the signature, simply add or remove it from the `SignedHeaders` section in the Authorization header. The extension should include all headers specified in that location in the signature it generates.
